export const company = {
  uf: "SC",
  cep: "89340000",
  qsa: [
    {
      pais: null,
      nome_socio: "VINICIUS ALFREDO SCHWALBE",
      codigo_pais: null,
      faixa_etaria: "Entre 21 a 30 anos",
      cnpj_cpf_do_socio: "***119199**",
      qualificacao_socio: "Sócio-Administrador",
      codigo_faixa_etaria: 3,
      data_entrada_sociedade: "2026-01-30",
      identificador_de_socio: 2,
      cpf_representante_legal: "***000000**",
      nome_representante_legal: "",
      codigo_qualificacao_socio: 49,
      qualificacao_representante_legal: "Não informada",
      codigo_qualificacao_representante_legal: 0,
    },
  ],
  cnpj: "64.857.627/0001-46",
  pais: null,
  email: null,
  porte: "MICRO EMPRESA",
  bairro: "CENTRO",
  numero: "304",
  ddd_fax: "",
  municipio: "ITAIOPOLIS",
  logradouro: "NEREU RAMOS",
  cnae_fiscal: 8640202,
  codigo_pais: null,
  complemento: "SALA 1",
  codigo_porte: 1,
  razao_social: "ITAIOPOLIS ANALISES CLINICAS LTDA",
  nome_fantasia: "EXAME CERTO",
  capital_social: 50000,
  ddd_telefone_1: "4736443741",
  ddd_telefone_2: "",
  opcao_pelo_mei: false,
  codigo_municipio: 8159,
  cnaes_secundarios: [],
  natureza_juridica: "Sociedade Empresária Limitada",
  regime_tributario: [],
  situacao_especial: "",
  opcao_pelo_simples: true,
  situacao_cadastral: 2,
  data_opcao_pelo_mei: null,
  data_exclusao_do_mei: null,
  cnae_fiscal_descricao: "Laboratórios clínicos",
  codigo_municipio_ibge: 4208104,
  data_inicio_atividade: "2026-01-30",
  data_situacao_especial: null,
  data_opcao_pelo_simples: "2026-02-02",
  data_situacao_cadastral: "2026-01-30",
  nome_cidade_no_exterior: "",
  codigo_natureza_juridica: 2062,
  data_exclusao_do_simples: null,
  motivo_situacao_cadastral: 0,
  ente_federativo_responsavel: "",
  identificador_matriz_filial: 1,
  qualificacao_do_responsavel: 49,
  descricao_situacao_cadastral: "ATIVA",
  descricao_tipo_de_logradouro: "RUA",
  descricao_motivo_situacao_cadastral: "SEM MOTIVO",
  descricao_identificador_matriz_filial: "MATRIZ",
};

/*
 * Dados tratados para exibir no site. O objeto acima vem cru da consulta de
 * CNPJ (tudo em maiúsculas e sem acentos), então os textos aqui são escritos à mão.
 */
const address = {
  street: "Rua Nereu Ramos, 304, Sala 1",
  district: "Centro",
  city: "Itaiópolis",
  state: company.uf,
  zip: "89340-000",
};

export const site = {
  name: "Exame Certo",
  legalName: "Itaiópolis Análises Clínicas Ltda.",
  description: "Laboratório de análises clínicas em Itaiópolis/SC.",
  cnpj: company.cnpj,
  phone: {
    display: "(47) 3644-3741",
    href: "tel:+554736443741",
  },
  address,
  mapsUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
    `${address.street}, ${address.district}, ${address.city} - ${address.state}, ${address.zip}`,
  )}`,
};
